### ISSUE TITLE
Cannot send messages to the user

### ISSUE THREAD

**Issue by matiego1** [matiego1/CountingBot#5]
```
[20:01:20] [Counting - JDA Callback 0/ERROR]: [net.dv8tion.jda.api.requests.RestAction] RestAction queue returned failure: [ErrorResponseException] 50007: Cannot send messages to this user
net.dv8tion.jda.api.exceptions.ContextException: null
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[counting.jar:?]
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:73) ~[counting.jar:?]
	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:200) ~[counting.jar:?]
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572) ~[counting.jar:?]
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538) ~[counting.jar:?]
	at me.matiego.counting.utils.Utils.lambda$sendPrivateMessage$0(Utils.java:234) ~[counting.jar:?]
	at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:117) ~[counting.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

```

**Comment by matiego1** [comment]
Fixed in https://github.com/matiego1/CountingBot/commit/b1815190faab98b69b3462b52683e0c4f31a9a58
